import { IContacts } from '../interface';

export const Contacts: IContacts[] = [
  {
    name: 'Junior Oliveira',
    avatar: 'assets/images/avatar/avatar-man-1.png',
    lastMessage: 'Ok, i will do it!',
    timeLastMessage: '4:46 pm',
    pinned: true,
    mute: false,
    unreadMessages: 2,
  },
  {
    name: 'Marcia Gonçalves',
    avatar: 'assets/images/avatar/avatar-woman-1.png',
    lastMessage: 'No problem, we can get it',
    timeLastMessage: '4:37 pm',
    pinned: true,
    mute: false,
    unreadMessages: 5,
  },
  {
    name: 'Caio Pereira',
    avatar: 'assets/images/avatar/avatar-man-2.png',
    lastMessage: 'Right',
    timeLastMessage: '4:12 pm',
    pinned: false,
    mute: true,
    unreadMessages: undefined,
  },
  {
    name: 'Vanessa Santos',
    avatar: 'assets/images/avatar/avatar-woman-2.png',
    lastMessage: 'Thank you :)',
    timeLastMessage: '3:32 pm',
    pinned: false,
    mute: false,
    unreadMessages: undefined,
  },
  {
    name: 'José da Silva',
    avatar: 'assets/images/avatar/avatar-man-3.png',
    lastMessage: 'I really appretiate that',
    timeLastMessage: '2:26 pm',
    pinned: false,
    mute: false,
    unreadMessages: 3,
  },
  {
    name: 'Maria Santana',
    avatar: 'assets/images/avatar/avatar-woman-3.png',
    lastMessage: 'I am sorry about it',
    timeLastMessage: '1:04 pm',
    pinned: false,
    mute: true,
    unreadMessages: 12,
  },
  {
    name: 'Carlos Campos',
    avatar: 'assets/images/avatar/avatar-man-4.png',
    lastMessage: 'I will be there',
    timeLastMessage: '12:00 pm',
    pinned: false,
    mute: true,
    unreadMessages: undefined,
  },
  {
    name: 'Suellen Souza',
    avatar: 'assets/images/avatar/avatar-woman-4.png',
    lastMessage: 'Ok, let\'s get it!!!',
    timeLastMessage: '11:15 am',
    pinned: false,
    mute: false,
    unreadMessages: undefined,
  },
];
